fix: console docker compose [ci skip]

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -14,9 +14,9 @@
 set -e
 
 command=$1
-[ "$ENV_DIR" == "" ] && env_unset=1
+[ "$ENV_DIR" = "" ] && env_unset=1
 ENV_DIR=${ENV_DIR:-$PWD}
-[ "$ENV_DIR" == "/home/app/stack" ] && ENV_DIR=$ENV_DIR/env
+[ "$ENV_DIR" = "/home/app/stack" ] && ENV_DIR=$ENV_DIR/env
 
 . bin/common.sh
 
@@ -33,9 +33,9 @@ function verbose_env() {
 }
 
 # VERBOSE - export this varibale to run this script in verbose mode
-VERBOSE=${VERBOSE:-"0"}
+VERBOSE=${VERBOSE:-'true'}
 # EXIT_FAST - export this varaibale to exit the script on error
-EXIT_FAST=${EXIT_FAST:-"1"}
+EXIT_FAST=${EXIT_FAST:-'true'}
 
 # check_kube_context - a flag to indicate to use kube context and to refresh kube access token before running command in docker
 check_kube_context=1
@@ -55,10 +55,10 @@ readme_url='https://github.com/redkubes/otomi-core'
 
 function set_env_and_stack_dir() {
   local cwd=$(basename "$PWD")
-  [ "$VERBOSE" == "1" ] && echo "CWD: $cwd"
-  if [[ "$cwd" == "otomi-core" ]]; then
-    [ "$env_unset" == "1" ] && echo "Error: The ENV_DIR environment variable is not set" && exit 1
-    [ "$VERBOSE" == "1" ] && echo "Mounting otomi-core dir"
+  [ "$VERBOSE" = "1" ] && echo "CWD: $cwd"
+  if [ "$cwd" = "otomi-core" ]; then
+    [ "$env_unset" = "1" ] && echo "Error: The ENV_DIR environment variable is not set" >&2 && exit 1
+    [ "$VERBOSE" = "1" ] && echo "Mounting otomi-core dir"
     stack_dir=$PWD
     mount_stack_dir=1
   fi
@@ -106,16 +106,15 @@ function check_docker_running() {
   if [ "$?" = "0" ]; then
     has_docker=1
   else
-    echo "Otomi CLI expects a running docker daemon!"
-    exit 1
+    echo "Otomi CLI expects a running docker daemon!" >&2 && exit 1
   fi
 }
 
 function evaluate_k8s_context() {
   local env_path="${ENV_DIR}/env/clouds/${CLOUD}/${CLUSTER}/.env"
-  [ ! -f $env_path ] && echo "Error: The file '${env_path}' does not exist" && exit 1
+  [ ! -f $env_path ] && echo "Error: The file '${env_path}' does not exist" >&2 && exit 1
   source $env_path
-  [[ -z "$K8S_CONTEXT" ]] && echo "Error: The K8S_CONTEXT env is not defined in $env_path" && exit 1
+  [[ -z "$K8S_CONTEXT" ]] && echo "Error: The K8S_CONTEXT env is not defined in $env_path" >&2 && exit 1
   return 0
 }
 
@@ -144,9 +143,9 @@ evaluate_secrets() {
     echo "Info: The 'secrets.*.yaml files' are not decrypted, because $ENV_DIR/.sops.yaml file is not present"
     return 0
   }
-  if [ "$CI" == "" ]; then
+  if [ "$CI" = "" ]; then
     local secrets_path="$ENV_DIR/.secrets"
-    [[ ! -r "$secrets_path" ]] && echo "Error: Unable to find the '$secrets_path' file.\nPlease follow to documentation: $readme_url" && exit 2
+    [[ ! -r "$secrets_path" ]] && echo "Error: Unable to find the '$secrets_path' file.\nPlease follow to documentation: $readme_url" >&2 && exit 2
     source $secrets_path
   fi
   prepare_crypt
@@ -155,13 +154,15 @@ evaluate_secrets() {
 
 validate_cluster_env() {
   evaluate_secrets
-  [[ -z "$CLOUD" ]] && echo "Error: The CLOUD environment variable is not set" && exit 2
-  [[ -z "$CLUSTER" ]] && echo "Error: The CLUSTER environment variable is not set" && exit 2
+  local err
+  [[ -z "$CLOUD" ]] && echo "Error: The CLOUD environment variable is not set" >&2 && err=1
+  [[ -z "$CLUSTER" ]] && echo "Error: The CLUSTER environment variable is not set" >&2 && err=1
+  [[ ! -z "$err" ]] && exit 2
   return 0
 }
 
 is_repo() {
-  [[ "$(basename "$PWD")" == "otomi-core" ]] && echo "Error: Should not be ran from otomi-core" && exit 2
+  [[ "$(basename "$PWD")" = "otomi-core" ]] && echo "Error: Should not be ran from otomi-core" >&2 && exit 2
   return 0
 }
 
@@ -188,7 +189,7 @@ function drun() {
   local socket_volume=''
 
   if [ "$CI" != "" ]; then
-    echo "Running in CI: $CI"
+    [ "$VERBOSE" = "1" ] && echo "Running in CI: $CI"
     check_kube_context=0
   else
     socket_volume="-v /var/run/docker.sock:/var/run/docker.sock"
@@ -205,15 +206,15 @@ function drun() {
     stack_volume="-v ${stack_dir}:${stack_dir}"
   fi
 
-  if [ "$VERBOSE" == "1" ]; then
+  if [ "$VERBOSE" = "1" ]; then
     verbose_env
   fi
 
   # use docker run if has_docker AND either:
   # - not in docker
   # - in docker AND force docker
-  if [[ ("$CI" == "") && $has_docker -eq 1 && ("$IN_DOCKER" != "1" || $dind -eq 1) ]]; then
-    [ "$VERBOSE" == "1" ] && echo "Running dockerized version of command: $command"
+  if [[ ("$CI" = "") && $has_docker -eq 1 && ("$IN_DOCKER" != "1" || $dind -eq 1) ]]; then
+    [ "$VERBOSE" = "1" ] && echo "Running dockerized version of command: $command"
     docker run $docker_terminal_params --rm \
       $stack_volume $socket_volume -v /tmp:/tmp \
       -v $GOOGLE_APPLICATION_CREDENTIALS:$GOOGLE_APPLICATION_CREDENTIALS \
@@ -237,7 +238,7 @@ function drun() {
       $cmd_image \
       $command
   else
-    [ "$VERBOSE" == "1" ] && echo "Running native version of command: $command"
+    [ "$VERBOSE" = "1" ] && echo "Running native version of command: $command"
     $command
   fi
 }
@@ -383,13 +384,12 @@ function execute() {
       ;;
     *)
       show_usage
-      [ "$1" != "" ] && echo "Error: Unknown command: $@"
-      exit 1
+      [ "$1" != "" ] && echo "Error: Unknown command: $@" >&2 && exit 1
       ;;
   esac
 }
 
-[[ -z "$command" ]] && echo "Error: Missing command argument" && show_usage && exit 2
+[[ -z "$command" ]] && echo "Error: Missing command argument" >&2 && show_usage && exit 2
 
 set_env_and_stack_dir
 set_otomi_image
