fix: fix previous conversations
Make the code allign more with the (Google) Style Guide

#271 #270

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -21,6 +21,10 @@ ENV_DIR=${ENV_DIR:-$PWD}
 
 . bin/common.sh
 
+if [ "${has_docker}" == "false" ]; then
+  err "Otomi CLI expects a running docker daemon!" && exit 1
+fi
+
 function verbose_env() {
   echo "has_docker=$has_docker"
   echo "ENV_DIR=$ENV_DIR"
@@ -54,7 +58,7 @@ function set_env_and_stack_dir() {
   local cwd=$(basename "$PWD")
   [ -n "$VERBOSE" ] && echo "CWD: $cwd"
   if [ "$cwd" = "otomi-core" ]; then
-    [ "$env_unset" = 'true' ] && print_error "The ENV_DIR environment variable is not set" && exit 1
+    [ "$env_unset" = 'true' ] && err "The ENV_DIR environment variable is not set" && exit 1
     [ -n "$VERBOSE" ] && echo "Mounting otomi-core dir"
     stack_dir=$PWD
     mount_stack_dir=1
@@ -98,17 +102,11 @@ function show_usage() {
   "
 }
 
-function check_docker_running() {
-  if [ "${has_docker}" = "0" ]; then
-    print_error "Otomi CLI expects a running docker daemon!" && exit 1
-  fi
-}
-
 function evaluate_k8s_context() {
   local env_path="${ENV_DIR}/env/clouds/${CLOUD}/${CLUSTER}/.env"
-  [ ! -f $env_path ] && print_error "The file '${env_path}' does not exist" && exit 1
+  [ ! -f $env_path ] && err "The file '${env_path}' does not exist" && exit 1
   source $env_path
-  [[ -z "$K8S_CONTEXT" ]] && print_error "The K8S_CONTEXT env is not defined in $env_path" && exit 1
+  [[ -z "$K8S_CONTEXT" ]] && err "The K8S_CONTEXT env is not defined in $env_path" && exit 1
   return 0
 }
 
@@ -138,7 +136,7 @@ function evaluate_secrets() {
   }
   if [ "$CI" = "" ]; then
     local secrets_path="$ENV_DIR/.secrets"
-    [[ ! -r "$secrets_path" ]] && print_error "Unable to find the '$secrets_path' file.\nPlease follow to documentation: $readme_url" && exit 2
+    [[ ! -r "$secrets_path" ]] && err "Unable to find the '$secrets_path' file.\nPlease follow to documentation: $readme_url" && exit 2
     source $secrets_path
   fi
   prepare_crypt
@@ -148,14 +146,14 @@ function evaluate_secrets() {
 function validate_cluster_env() {
   evaluate_secrets
   local err
-  [[ -z "$CLOUD" ]] && print_error "The CLOUD environment variable is not set" && err=1
-  [[ -z "$CLUSTER" ]] && print_error "The CLUSTER environment variable is not set" && err=1
+  [[ -z "$CLOUD" ]] && err "The CLOUD environment variable is not set" && err=1
+  [[ -z "$CLUSTER" ]] && err "The CLUSTER environment variable is not set" && err=1
   [[ -n "$err" ]] && exit 2
   return 0
 }
 
 function is_repo() {
-  [[ "$(basename "$PWD")" = "otomi-core" ]] && print_error "Error: Should not be ran from otomi-core" && exit 2
+  [[ "$(basename "$PWD")" = "otomi-core" ]] && err "Error: Should not be ran from otomi-core" && exit 2
   return 0
 }
 
@@ -206,7 +204,7 @@ function drun() {
   # use docker run if has_docker AND either:
   # - not in docker
   # - in docker AND force docker
-  if [[ $has_docker -eq 1 && ("$IN_DOCKER" != "1" || $dind -eq 1) ]]; then
+  if [[ "${has_docker}" == 'true' && "$IN_DOCKER" != '1' ]]; then
     [ -n "$VERBOSE" ] && echo "Running dockerized version of command: $command"
     docker run $docker_terminal_params --rm \
       $stack_volume $socket_volume -v /tmp:/tmp \
@@ -243,7 +241,7 @@ function execute() {
       check_kube_context=0
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER -f helmfile.tpl/helmfile-dump.yaml build | grep -Ev $helmfileOutputHide | sed -e $replacePathsPattern
+      drun helmfile -e $CLOUD-$CLUSTER -f helmfile.tpl/helmfile-dump.yaml build | grep -Ev $helmfile_output_hide | sed -e $replace_paths_pattern
       ;;
     test)
       validate_cluster_env
@@ -252,12 +250,12 @@ function execute() {
     hf)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER $@ | grep -Ev $helmfile_output_hide
       ;;
     apply)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ apply --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER $@ apply --skip-deps | grep -Ev $helmfile_output_hide
       ;;
     bash)
       check_kube_context=0
@@ -290,17 +288,17 @@ function execute() {
       ;;
     deploy)
       validate_cluster_env
-      drun bin/deploy.sh | grep -Ev $helmfileOutputHide
+      drun bin/deploy.sh | grep -Ev $helmfile_output_hide
       ;;
     diff)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ diff --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER $@ diff --skip-deps | grep -Ev $helmfile_output_hide
       ;;
     destroy)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ destroy | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER $@ destroy | grep -Ev $helmfile_output_hide
       ;;
     encrypt)
       check_sops_file
@@ -319,13 +317,13 @@ function execute() {
     sync)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ sync --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER $@ sync --skip-deps | grep -Ev $helmfile_output_hide
       ;;
     template)
       check_kube_context=0
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER --quiet $@ template --skip-deps | grep -Ev $helmfileOutputHideTpl
+      drun helmfile -e $CLOUD-$CLUSTER --quiet $@ template --skip-deps | grep -Ev $helmfile_output_hide_tpl
       ;;
     rotate-keys)
       check_sops_file
@@ -383,15 +381,14 @@ function execute() {
       ;;
     *)
       show_usage
-      [ -z "$1" ] && print_error "Unknown command: $@" && exit 1
+      [ -z "$1" ] && err "Unknown command: $@" && exit 1
       ;;
   esac
 }
 
-[ -z "$command" ] && print_error "Missing command argument" && show_usage && exit 2
+[ -z "$command" ] && err "Missing command argument" && show_usage && exit 2
 
 set_env_and_stack_dir
 set_otomi_image
 set_helm_config
-check_docker_running
 execute $command $@
