refactor: refactor policy params parsing for new schema structure

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -232,140 +232,140 @@ function drun() {
 function execute() {
   shift 2
   case $command in
-  values)
-    check_kube_context=0
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER -f helmfile.tpl/helmfile-dump.yaml build | grep -Ev $helmfileOutputHide | sed -e $replacePathsPattern
-    ;;
-  test)
-    validate_cluster_env
-    drun bin/test.sh
-    ;;
-  hf)
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER $@ | grep -Ev $helmfileOutputHide
-    ;;
-  apply)
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER $@ apply --skip-deps | grep -Ev $helmfileOutputHide
-    ;;
-  bash)
-    check_kube_context=0
-    docker_terminal_params='-it'
-    drun bash
-    ;;
-  bootstrap)
-    check_kube_context=0
-    validate_cluster_env
-    drun bin/bootstrap.sh 1
-    ;;
-  console)
-    check_kube_context=0
-    bin/console.sh $@
-    ;;
-  decrypt)
-    check_sops_file
-    check_kube_context=0
-    evaluate_secrets
-    if [ "$@" != "" ]; then
-      for f in $@; do
-        echo "Decrypting $f"
-        drun helm secrets dec ./env/$f >/dev/null
-      done
-      exit
-    fi
-    drun bin/crypt.sh decrypt
-    ;;
-  deploy)
-    validate_cluster_env
-    drun bin/deploy.sh | grep -Ev $helmfileOutputHide
-    ;;
-  diff)
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER $@ diff --skip-deps | grep -Ev $helmfileOutputHide
-    ;;
-  encrypt)
-    check_sops_file
-    check_kube_context=0
-    evaluate_secrets
-    if [ "$@" != "" ]; then
-      for f in $@; do
-        echo "Encrypting $f"
-        drun helm secrets enc ./env/$f >/dev/null
-      done
-      exit
-    fi
-    drun bin/crypt.sh encrypt
-    ;;
-  sync)
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER $@ sync --skip-deps | grep -Ev $helmfileOutputHide
-    ;;
-  template)
-    check_kube_context=0
-    validate_cluster_env
-    set -o pipefail
-    drun helmfile -e $CLOUD-$CLUSTER --quiet $@ template --skip-deps | grep -Ev $helmfileOutputHideTpl
-    ;;
-  rotate-keys)
-    check_sops_file
-    check_kube_context=0
-    evaluate_secrets
-    drun bin/crypt.sh rotate
-    ;;
-  switch)
-    evaluate_k8s_context
-    kubectl config use $K8S_CONTEXT
-    drun bin/bootstrap.sh 1
-    ;;
-  test)
-    validate_cluster_env
-    drun bin/test.sh
-    drun $@
-    ;;
-  validate-templates)
-    evaluate_secrets
-    drun bin/validate-templates.sh
-    ;;
-  validate-policies)
-    validate_cluster_env
-    drun bin/validate-policies.sh
-    ;;
-  x)
-    check_kube_context=0
-    drun $@
-    ;;
-  commit)
-    check_kube_context=0
-    is_repo
-    evaluate_secrets
-    git -C $ENV_DIR pull
-    drun bin/validate-all.sh
-    drun bin/pre-commit.sh
-    git add . && git commit -m 'Manual commit' --no-verify
-    ;;
-  pull)
-    check_kube_context=0
-    is_repo
-    evaluate_secrets
-    git -C $ENV_DIR pull
-    drun bin/bootstrap.sh 1
-    ;;
-  validate-values)
-    check_kube_context=0
-    evaluate_secrets
-    drun bin/validate-all.sh
-    ;;
-  *)
-    show_usage
-    [ "$1" != "" ] && echo "Error: Unknown command: $@"
-    exit 1
-    ;;
+    values)
+      check_kube_context=0
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER -f helmfile.tpl/helmfile-dump.yaml build | grep -Ev $helmfileOutputHide | sed -e $replacePathsPattern
+      ;;
+    test)
+      validate_cluster_env
+      drun bin/test.sh
+      ;;
+    hf)
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER $@ | grep -Ev $helmfileOutputHide
+      ;;
+    apply)
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER $@ apply --skip-deps | grep -Ev $helmfileOutputHide
+      ;;
+    bash)
+      check_kube_context=0
+      docker_terminal_params='-it'
+      drun bash
+      ;;
+    bootstrap)
+      check_kube_context=0
+      validate_cluster_env
+      drun bin/bootstrap.sh 1
+      ;;
+    console)
+      check_kube_context=0
+      bin/console.sh $@
+      ;;
+    decrypt)
+      check_sops_file
+      check_kube_context=0
+      evaluate_secrets
+      if [ "$@" != "" ]; then
+        for f in $@; do
+          echo "Decrypting $f"
+          drun helm secrets dec ./env/$f >/dev/null
+        done
+        exit
+      fi
+      drun bin/crypt.sh decrypt
+      ;;
+    deploy)
+      validate_cluster_env
+      drun bin/deploy.sh | grep -Ev $helmfileOutputHide
+      ;;
+    diff)
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER $@ diff --skip-deps | grep -Ev $helmfileOutputHide
+      ;;
+    encrypt)
+      check_sops_file
+      check_kube_context=0
+      evaluate_secrets
+      if [ "$@" != "" ]; then
+        for f in $@; do
+          echo "Encrypting $f"
+          drun helm secrets enc ./env/$f >/dev/null
+        done
+        exit
+      fi
+      drun bin/crypt.sh encrypt
+      ;;
+    sync)
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER $@ sync --skip-deps | grep -Ev $helmfileOutputHide
+      ;;
+    template)
+      check_kube_context=0
+      validate_cluster_env
+      set -o pipefail
+      drun helmfile -e $CLOUD-$CLUSTER --quiet $@ template --skip-deps | grep -Ev $helmfileOutputHideTpl
+      ;;
+    rotate-keys)
+      check_sops_file
+      check_kube_context=0
+      evaluate_secrets
+      drun bin/crypt.sh rotate
+      ;;
+    switch)
+      evaluate_k8s_context
+      kubectl config use $K8S_CONTEXT
+      drun bin/bootstrap.sh 1
+      ;;
+    test)
+      validate_cluster_env
+      drun bin/test.sh
+      drun $@
+      ;;
+    validate-templates)
+      evaluate_secrets
+      drun bin/validate-templates.sh
+      ;;
+    validate-policies)
+      evaluate_secrets
+      drun bin/validate-policies.sh
+      ;;
+    x)
+      check_kube_context=0
+      drun $@
+      ;;
+    commit)
+      check_kube_context=0
+      is_repo
+      evaluate_secrets
+      git -C $ENV_DIR pull
+      drun bin/validate-all.sh
+      drun bin/pre-commit.sh
+      git add . && git commit -m 'Manual commit' --no-verify
+      ;;
+    pull)
+      check_kube_context=0
+      is_repo
+      evaluate_secrets
+      git -C $ENV_DIR pull
+      drun bin/bootstrap.sh 1
+      ;;
+    validate-values)
+      check_kube_context=0
+      evaluate_secrets
+      drun bin/validate-all.sh
+      ;;
+    *)
+      show_usage
+      [ "$1" != "" ] && echo "Error: Unknown command: $@"
+      exit 1
+      ;;
   esac
 }
 
