fix: metrics server for aws, drone image, #137 [ci skip]

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -12,6 +12,7 @@
 ##
 #####################################################################################
 set -e
+[ "$ENV_DIR" == "" ] && env_unset=1
 ENV_DIR=${ENV_DIR:-$PWD}
 [ "$ENV_DIR" == "/home/app/stack" ] && ENV_DIR=$ENV_DIR/env
 
@@ -53,6 +54,18 @@ cmd_image=''
 docker_terminal_params='-it'
 helm_config=''
 readme_url='https://github.com/redkubes/otomi-stack'
+
+function set_env_and_stack_dir() {
+  local cwd=$(basename "$PWD")
+  [ "$VERBOSE" == "1" ] && echo "CWD: $cwd"
+  if [[ "$cwd" == "otomi-stack" ]]; then
+    [ "$env_unset" == "1" ] && echo "Error: The ENV_DIR environment variable is not set" && exit 2
+    [ "$VERBOSE" == "1" ] && echo "Mounting otomi-stack dir"
+    stack_dir=$PWD
+    mount_stack_dir=1
+  fi
+  return 0
+}
 
 function set_helm_config() {
   helm_config="$HOME/.config/helm"
@@ -137,7 +150,7 @@ validate_cluster_env() {
 }
 
 is_repo() {
-  [[ "$(basename "$PWD")" == 'otomi-stack' ]] && "Error: Should not be ran from otomi-stack" && exit 2
+  [[ "$(basename "$PWD")" == "otomi-stack" ]] && "Error: Should not be ran from otomi-stack" && exit 2
   return 0
 }
 
@@ -316,18 +329,6 @@ function execute() {
     exit 1
     ;;
   esac
-}
-
-function set_env_and_stack_dir() {
-  local cwd=$(basename "$PWD")
-  [ "$VERBOSE" == "1" ] && echo "CWD: $cwd"
-  if [[ "$cwd" == "otomi-stack" ]]; then
-    [ "$VERBOSE" == "1" ] && echo "Mounting otomi-stack dir"
-    [[ -z "$ENV_DIR" ]] && echo "Error: The ENV_DIR environment variable is not set" && exit 2
-    stack_dir=$PWD
-    mount_stack_dir=1
-  fi
-  return 0
 }
 
 [[ -z "$command" ]] && echo "Error: Missing command argument" && show_usage && exit 2
