fix: together with @Morriz "cleaned up" the codebase
Removed a couple of "configurable" options and made them hard coded as well as fixing a couple of
bash issues like `"$@"`

#261 #288

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -262,12 +262,12 @@ function execute() {
     hf)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER "$@" | grep -Ev $helmfileOutputHide
       ;;
     apply)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ apply --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER "$@" apply --skip-deps | grep -Ev $helmfileOutputHide
       ;;
     bash)
       check_kube_context=0
@@ -276,7 +276,7 @@ function execute() {
       ;;
     bootstrap)
       check_kube_context=0
-      if [[ "$@" != '' ]]; then
+      if [[ "$*" != '' ]]; then
         validate_cluster_env
       fi
       drun bin/bootstrap.sh 1
@@ -284,14 +284,14 @@ function execute() {
     console)
       check_kube_context=0
       evaluate_secrets
-      run_console $@
+      run_console "$@"
       ;;
     decrypt)
       check_sops_file
       check_kube_context=0
       evaluate_secrets
-      if [[ "$@" != '' ]]; then
-        for f in $@; do
+      if [[ "$*" != '' ]]; then
+        for f in "$@"; do
           echo "Decrypting $f"
           drun helm secrets dec ./env/$f >/dev/null
         done
@@ -307,19 +307,19 @@ function execute() {
     diff)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ diff --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER "$@" diff --skip-deps | grep -Ev $helmfileOutputHide
       ;;
     destroy)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ destroy | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER "$@" destroy | grep -Ev $helmfileOutputHide
       ;;
     encrypt)
       check_sops_file
       check_kube_context=0
       evaluate_secrets
-      if [[ "$@" != '' ]]; then
-        for f in $@; do
+      if [[ "$*" != '' ]]; then
+        for f in "$@"; do
           echo "Encrypting $f"
           drun helm secrets enc ./env/$f >/dev/null
         done
@@ -331,13 +331,13 @@ function execute() {
     sync)
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER $@ sync --skip-deps | grep -Ev $helmfileOutputHide
+      drun helmfile -e $CLOUD-$CLUSTER "$@" sync --skip-deps | grep -Ev $helmfileOutputHide
       ;;
     template)
       check_kube_context=0
       validate_cluster_env
       set -o pipefail
-      drun helmfile -e $CLOUD-$CLUSTER --quiet $@ template --skip-deps | grep -Ev $helmfileOutputHideTpl
+      drun helmfile -e $CLOUD-$CLUSTER --quiet "$@" template --skip-deps | grep -Ev $helmfileOutputHideTpl
       ;;
     rotate-keys)
       check_sops_file
@@ -355,22 +355,17 @@ function execute() {
       evaluate_secrets
       drun bin/gen-drone.sh
       ;;
-    test)
-      validate_cluster_env
-      evaluate_secrets
-      drun bin/test.sh
-      ;;
     validate-templates)
-      if [[ "$@" != '' ]]; then
+      if [[ "$*" != '' ]]; then
         validate_cluster_env
       fi
       check_kube_context=0
       evaluate_secrets
-      drun bin/validate-templates.sh $@
+      drun bin/validate-templates.sh "$@"
       ;;
     x)
       check_kube_context=0
-      drun $@
+      drun "$@"
       ;;
     commit)
       check_kube_context=0
@@ -395,7 +390,7 @@ function execute() {
       ;;
     *)
       show_usage
-      [ -z "$1" ] && echo "Error: Unknown command: $@" >&2 && exit 1
+      [ -z "$1" ] && echo "Error: Unknown command: $*" >&2 && exit 1
       ;;
   esac
 }
@@ -406,4 +401,4 @@ set_env_and_stack_dir
 set_otomi_image
 set_helm_config
 check_docker_running
-execute $command $@
+execute $command "$@"
