feat: add kubeval command to otomi cli

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -31,13 +31,13 @@ docker_terminal_params=''
 helm_config=''
 readme_url='https://github.com/redkubes/otomi-stack'
 
-function set_helm_config {
+function set_helm_config() {
   helm_config="$HOME/.config/helm"
   uname -a | grep -i darwin >/dev/null && helm_config="$HOME/Library/Preferences/helm"
   return 0
 }
 
-function show_usage {
+function show_usage() {
   echo "The $0 usage:
     aws - run CLI AWS
     az - run CLI for Azure
@@ -55,13 +55,14 @@ function show_usage {
     helmfile-values - show merged values 
     helmfile-template - run helmfile template
     helmfile-template-quiet - run helmfile template (only print yaml documents)
+    kubeval - run kubeval resource validation 
     help - print this help
     kubectl - run kubectl
     pull - wraper for git-pull (encrypt -> generate pipelines -> commit changes)
   "
 }
 
-function evaluate_k8s_context {
+function evaluate_k8s_context() {
   local env_sh_path="${env_dir}/env/${CLOUD}/${CLUSTER}.sh"
   [ ! -f $env_sh_path ] && echo "Error: The file '${env_sh_path}' does not exist" && exit 1
   source $env_sh_path
@@ -69,13 +70,13 @@ function evaluate_k8s_context {
   return 0
 }
 
-function validate_k8s_context {
+function validate_k8s_context() {
   local context=$(kubectl config current-context)
   [[ "$K8S_CONTEXT" != "$context" ]] && echo "Error: Your current kubernetes context does not match expected one: $K8S_CONTEXT" && exit 1
   return 0
 }
 
-function set_env_ini {
+function set_env_ini() {
   local init_path=$env_dir/env.ini
   [ ! -f $init_path ] && echo "Error: The file '${init_path}' does not exist" && exit 1
   source $init_path
@@ -100,6 +101,25 @@ validate_required_env() {
   [[ -z "$CLUSTER" ]] && echo "Error: The CLUSTER environment variable is not set" && exit 2
   [[ -z "$GCLOUD_SERVICE_KEY" ]] && echo "Error: The GCLOUD_SERVICE_KEY environment variable is not set" && exit 2
   return 0
+}
+
+function test_pass() {
+  echo "Validation Success;"
+  rm -rf /tmp/kubeval-fixtures/
+  exit 0
+}
+function test_fail() {
+  echo "Validation Failed;"
+  rm -rf /tmp/kubeval-fixtures/
+  exit 1
+}
+function kube_validate() {
+  local k8s_version=${1:-1.16.0}
+  MOUNT_TMP_DIR=1
+  echo "Generating Manifests in tmp location and checking Otomi Stack against Kubernetes Version: ${k8s_version}"
+  # using OUTPUT-DIR parameter because kubeval is not accepting multiple resources per file
+  drun helmfile -e ${CLOUD}-$CLUSTER --quiet template --skip-deps --output-dir=/tmp/kubeval-fixtures >/dev/null
+  ( (kubeval --force-color -d /tmp/kubeval-fixtures --strict --ignore-missing-schemas --kubernetes-version $k8s_version) || test_fail) && test_pass
 }
 
 function drun() {
@@ -148,105 +168,108 @@ function drun() {
     $command
 }
 
-function execute {
-    case $command in
-    helm)
-      drun helm "${@:2}"
-      break
-      ;;
-    helmfile)
-      drun helmfile -e ${CLOUD}-$CLUSTER "${@:2}" --skip-deps
-      break
-      ;;
-    helmfile-raw)
-      drun helmfile "${@:2}"
-      break
-      ;;
-    helmfile-values)
-      drun helmfile -f helmfile.tpl/helmfile-dump.yaml build
-      break
-      ;;
-    helmfile-template)
-      drun helmfile -e ${CLOUD}-$CLUSTER "${@:2}" template --skip-deps
-      break
-      ;;
-    helmfile-template-quiet)
-      drun helmfile -e ${CLOUD}-$CLUSTER --quiet "${@:2}" template --skip-deps | grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -vi skipping | grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -vi "helmfile-"
-      break
-      ;;
-    aws)
-      set_kube_context=0
-      drun aws "${@:2}"
-      break
-      ;;
-    az)
-      set_kube_context=0
-      drun az "${@:2}"
-      break
-      ;;
-    eksctl)
-      set_kube_context=0
-      drun eksctl "${@:2}"
-      break
-      ;; 
-    gcloud)
-      set_kube_context=0
-      drun gcloud "${@:2}"
-      break
-      ;;
-    deploy)
-      drun bin/deploy.sh
-      break
-      ;;
-    encrypt)
-      set_kube_context=0
-      drun bin/crypt.sh enc
-      break
-      ;;
-    decrypt)
-      set_kube_context=0
-      drun bin/crypt.sh dec
-      break
-      ;;
-    bash)
-      set_kube_context=0
-      docker_terminal_params='-it'
-      drun bash
-      break
-      ;;
-    help)
-      show_usage
-      break
-      ;;
-    exec)
-      set_kube_context=0
-      drun "${@:2}"
-      break
-      ;;
-    kubectl)
-      drun kubectl "${@:2}"
-      break
-      ;;
-    commit)
-      set_kube_context=0
-      drun bin/git-commit.sh
-      break
-      ;;
-    pull)
-      set_kube_context=0
-      drun bin/git-pull.sh
-      break
-      ;;
-    *)
-      show_usage
-      echo "Error: Unknown command: $@"
-      exit 1
-      ;;
-    esac
+function execute() {
+  case $command in
+  helm)
+    drun helm "${@:2}"
+    break
+    ;;
+  helmfile)
+    drun helmfile -e ${CLOUD}-$CLUSTER "${@:2}" --skip-deps
+    break
+    ;;
+  helmfile-raw)
+    drun helmfile "${@:2}"
+    break
+    ;;
+  helmfile-values)
+    drun helmfile -f helmfile.tpl/helmfile-dump.yaml build
+    break
+    ;;
+  helmfile-template)
+    drun helmfile -e ${CLOUD}-$CLUSTER "${@:2}" template --skip-deps
+    break
+    ;;
+  helmfile-template-quiet)
+    drun helmfile -e ${CLOUD}-$CLUSTER --quiet "${@:2}" template --skip-deps | grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -vi skipping | grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -vi "helmfile-"
+    break
+    ;;
+  kubeval)
+    kube_validate "${@:2}"
+    break
+    ;;
+  aws)
+    set_kube_context=0
+    drun aws "${@:2}"
+    break
+    ;;
+  az)
+    set_kube_context=0
+    drun az "${@:2}"
+    break
+    ;;
+  eksctl)
+    set_kube_context=0
+    drun eksctl "${@:2}"
+    break
+    ;;
+  gcloud)
+    set_kube_context=0
+    drun gcloud "${@:2}"
+    break
+    ;;
+  deploy)
+    drun bin/deploy.sh
+    break
+    ;;
+  encrypt)
+    set_kube_context=0
+    drun bin/crypt.sh enc
+    break
+    ;;
+  decrypt)
+    set_kube_context=0
+    drun bin/crypt.sh dec
+    break
+    ;;
+  bash)
+    set_kube_context=0
+    docker_terminal_params='-it'
+    drun bash
+    break
+    ;;
+  help)
+    show_usage
+    break
+    ;;
+  exec)
+    set_kube_context=0
+    drun "${@:2}"
+    break
+    ;;
+  kubectl)
+    drun kubectl "${@:2}"
+    break
+    ;;
+  commit)
+    set_kube_context=0
+    drun bin/git-commit.sh
+    break
+    ;;
+  pull)
+    set_kube_context=0
+    drun bin/git-pull.sh
+    break
+    ;;
+  *)
+    show_usage
+    echo "Error: Unknown command: $@"
+    exit 1
+    ;;
+  esac
 }
 
-
-function verbose_env {
+function verbose_env() {
   echo "env_dir=$env_dir"
   echo "stack_dir=$stack_dir"
   echo "helm_config=$helm_config"
@@ -255,7 +278,7 @@ function verbose_env {
   echo "K8S_CONTEXT=$K8S_CONTEXT"
 }
 
-function set_env_and_stack_dir {
+function set_env_and_stack_dir() {
   local cwd=$(basename "$PWD")
 
   if [[ "$cwd" == 'otomi-stack' ]]; then
