fix: small things

diff --git a/bin/otomi b/bin/otomi
--- a/bin/otomi
+++ b/bin/otomi
@@ -13,6 +13,9 @@
 #####################################################################################
 set -e
 
+# normalize $CI to be set to 'true' if set and not 'false'
+[ -n "$CI" ] && [ "$CI" != 'false' ] && export CI='true'
+
 command=$1
 env_unset='false'
 [ "$ENV_DIR" = "" ] && env_unset='true'
@@ -33,9 +36,6 @@ function verbose_env() {
   echo "command=$command"
 }
 
-# VERBOSE - set this variable to run this script in verbose mode
-VERBOSE=${VERBOSE:-''}
-
 # check_kube_context - a flag to indicate to use kube context and to refresh kube access token before running command in docker
 check_kube_context=1
 # A path to directory with values directory
@@ -54,10 +54,10 @@ readme_url='https://github.com/redkubes/otomi-core'
 
 function set_env_and_stack_dir() {
   local cwd=$(basename "$PWD")
-  [ -n "$VERBOSE" ] && echo "CWD: $cwd"
+  [ "${VERBOSE-}" != '' ] && echo "CWD: $cwd"
   if [ "$cwd" = "otomi-core" ]; then
     [ "$env_unset" = 'true' ] && echo "Error: The ENV_DIR environment variable is not set" >&2 && exit 1
-    [ -n "$VERBOSE" ] && echo "Mounting otomi-core dir"
+    [ "${VERBOSE-}" != '' ] && echo "Mounting otomi-core dir"
     stack_dir=$PWD
     mount_stack_dir=1
   fi
@@ -114,7 +114,7 @@ function evaluate_k8s_context() {
   local env_path="${ENV_DIR}/env/clouds/${CLOUD}/${CLUSTER}/.env"
   [ ! -f $env_path ] && echo "Error: The file '${env_path}' does not exist" >&2 && exit 1
   source $env_path
-  [[ -z "$K8S_CONTEXT" ]] && echo "Error: The K8S_CONTEXT env is not defined in $env_path" >&2 && exit 1
+  [ -z "$K8S_CONTEXT" ] && echo "Error: The K8S_CONTEXT env is not defined in $env_path" >&2 && exit 1
   return 0
 }
 
@@ -124,7 +124,7 @@ function validate_k8s_context() {
     read -p "Warning: Your current kubernetes context does not match target context: $K8S_CONTEXT. Would you like to switch kube context to target first? Yn" oki
     if [ "${oki:-y}" = "y" ]; then
       kubectl config use $K8S_CONTEXT
-      drun bin/bootstrap.sh 1
+      $is_repo && drun bin/bootstrap.sh 1
     else
       exit
     fi
@@ -142,7 +142,7 @@ evaluate_secrets() {
     echo "Info: The 'secrets.*.yaml files' are not decrypted, because $ENV_DIR/.sops.yaml file is not present"
     return 0
   }
-  if [ "$CI" = "" ]; then
+  if [ "$CI" != 'true' ]; then
     local secrets_path="$ENV_DIR/.secrets"
     [[ ! -r "$secrets_path" ]] && echo "Error: Unable to find the '$secrets_path' file.\nPlease follow to documentation: $readme_url" >&2 && exit 2
     source $secrets_path
@@ -160,8 +160,11 @@ validate_cluster_env() {
   return 0
 }
 
-is_repo() {
-  [[ "$(basename "$PWD")" = "otomi-core" ]] && echo "Error: Should not be ran from otomi-core" >&2 && exit 2
+[ "$(basename "$PWD")" = "otomi-core" ]
+is_repo=$1
+
+check_repo() {
+  $is_repo && echo "Error: Should not be ran from otomi-core" >&2 && exit 2
   return 0
 }
 
@@ -187,8 +190,8 @@ function drun() {
   local stack_volume=''
   local socket_volume=''
 
-  [ -n "$VERBOSE" ] && echo "Running in CI: $CI"
-  if [ -n "$CI" ]; then
+  [ "${VERBOSE-}" != '' ] && echo "Running in CI: $CI"
+  if [ "$CI" = 'true' ]; then
     check_kube_context=0
   else
     socket_volume="-v /var/run/docker.sock:/var/run/docker.sock"
@@ -205,7 +208,7 @@ function drun() {
     stack_volume="-v ${stack_dir}:${stack_dir}"
   fi
 
-  if [ -n "$VERBOSE" ]; then
+  if [ "${VERBOSE-}" != '' ]; then
     verbose_env
   fi
 
@@ -213,7 +216,7 @@ function drun() {
   # - not in docker
   # - in docker AND force docker
   if [[ $has_docker -eq 1 && ("$IN_DOCKER" != "1" || $dind -eq 1) ]]; then
-    [ -n "$VERBOSE" ] && echo "Running dockerized version of command: $command"
+    [ "${VERBOSE-}" != '' ] && echo "Running dockerized version of command: $command"
     docker run $docker_terminal_params --rm \
       $stack_volume $socket_volume -v /tmp:/tmp \
       -v $GOOGLE_APPLICATION_CREDENTIALS:$GOOGLE_APPLICATION_CREDENTIALS \
@@ -226,7 +229,7 @@ function drun() {
       -v ${ENV_DIR}:${stack_dir}/env \
       -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
       -e CUSTOMER="$customer" \
-      -e VERBOSE="$VERBOSE" \
+      -e VERBOSE="${VERBOSE-}" \
       -e CLOUD="$CLOUD" \
       -e IN_DOCKER="1" \
       -e GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY" \
@@ -237,7 +240,7 @@ function drun() {
       $cmd_image \
       $command
   else
-    [ -n "$VERBOSE" ] && echo "Running native version of command: $command"
+    [ "${VERBOSE-}" != '' ] && echo "Running native version of command: $command"
     $command
   fi
 }
@@ -267,7 +270,7 @@ function execute() {
       ;;
     bash)
       check_kube_context=0
-      docker_terminal_params='-t'
+      docker_terminal_params='-ti'
       drun bash
       ;;
     bootstrap)
@@ -349,29 +352,26 @@ function execute() {
       evaluate_secrets
       drun bin/test.sh
       ;;
-    validate-policies)
-      if [[ "$@" != '' ]]; then
-        validate_cluster_env
-      fi
+    validate-values)
       check_kube_context=0
       evaluate_secrets
-      drun bin/validate-policies.sh
+      drun bin/validate-values.sh
       ;;
     validate-templates)
-      if [[ "$@" != '' ]]; then
-        validate_cluster_env
-      fi
+      validate_cluster_env
       check_kube_context=0
       evaluate_secrets
       drun bin/validate-templates.sh $@
       ;;
-    x)
+    validate-policies)
+      validate_cluster_env
       check_kube_context=0
-      drun $@
+      evaluate_secrets
+      drun bin/validate-policies.sh $@
       ;;
     commit)
       check_kube_context=0
-      is_repo
+      check_repo
       evaluate_secrets
       git -C $ENV_DIR pull
       drun bin/validate-values.sh
@@ -380,15 +380,14 @@ function execute() {
       ;;
     pull)
       check_kube_context=0
-      is_repo
+      check_repo
       evaluate_secrets
       git -C $ENV_DIR pull
       drun bin/bootstrap.sh 1
       ;;
-    validate-values)
+    x)
       check_kube_context=0
-      evaluate_secrets
-      drun bin/validate-values.sh
+      drun $@
       ;;
     *)
       show_usage
