feat: 🎸 make hf lint run through new cli & fix gen-drone

diff --git a/binzx/otomi b/binzx/otomi
--- a/binzx/otomi
+++ b/binzx/otomi
@@ -143,19 +143,34 @@ silent echo "Checking for updates"
 silent echo "Preparing docker environment variables"
 tmp_env=$(mktemp)
 
+function dump_variable() {
+  var=$1
+  echo "$var=${!var}" >> $tmp_env
+}
+dump_variable ENV_DIR
+dump_variable AZURE_TENANT_ID
+dump_variable AZURE_CLIENT_ID
+dump_variable AZURE_CLIENT_SECRET
+dump_variable AWS_REGION
+dump_variable AWS_ACCESS_KEY_ID
+dump_variable AWS_SECRET_ACCESS_KEY
+dump_variable VAULT_TOKEN
+dump_variable GCLOUD_SERVICE_KEY
+dump_variable K8S_CONTEXT
+dump_variable KUBE_VERSION_OVERRIDE
+dump_variable CI
+dump_variable TESTING
+dump_variable TRACE
+dump_variable PROFILE
+dump_variable DRY_RUN
+dump_variable DOCKER_SERVER
+dump_variable DOCKER_USERNAME
+dump_variable DOCKER_PASSWORD
+dump_variable OTOMI_TAG
+dump_variable STATIC_COLORS
+
 cat >>$tmp_env <<EOF
-ENV_DIR=${ENV_DIR}
-AZURE_TENANT_ID=${AZURE_TENANT_ID}
-AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
-AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
-AWS_REGION=${AWS_REGION}
-AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
-AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
-VAULT_TOKEN=${VAULT_TOKEN}
-GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}
-K8S_CONTEXT=${K8S_CONTEXT}
 SHELL=${path_to_exec_shell}
-OTOMI_TAG=${OTOMI_TAG}
 OTOMI_CALLER_COMMAND=${BASH_SOURCE[0]##*/}
 OTOMI_IN_DOCKER=true
 EOF
@@ -205,11 +220,13 @@ fi
 
 silent echo "Pulling latest version of the docker image"
 # TODO: Remove otomi-zx check
-[ "$OTOMI_TAG" = 'latest' ] || [ "$OTOMI_TAG" = 'master' ] || [ "$OTOMI_TAG" = 'otomi-zx' ] && [ -z $NOPULL ] && silent docker pull $otomi_tools_image
-status=$?
-if [ "$status" -ne 0 ]; then
-  echo "Could not find an image for the supplied OTOMI_TAG: '${OTOMI_TAG}'"
-  exit $status
+if [ "$OTOMI_TAG" = 'latest' ] || [ "$OTOMI_TAG" = 'master' ] || [ "$OTOMI_TAG" = 'otomi-zx' ] && [ -z $NOPULL ]; then 
+  silent docker pull $otomi_tools_image
+  status=$?
+  if [ "$status" -ne 0 ]; then
+    echo "Could not find an image for the supplied OTOMI_TAG: '${OTOMI_TAG}'"
+    exit $status
+  fi
 fi
 mkdir -p /tmp/otomi
 docker run --network host --rm -it \
@@ -236,9 +253,9 @@ if [[ $calling_args == *'-skip-cleanup'* ]] || [[ $calling_args == *'-s'* ]]; th
   running_date=$(date -u '+%y%m%d-%H%M')
   backup_path="/tmp/otomi/otomi-$running_date"
   mkdir -p "$backup_path"
-  mv "$tmp_volume_dir/otomi" "$backup_path"
   mv "$tmp_env" "$backup_path/running_env"
 else
+  sleep 0.1
   rm -f "$tmp_env"
   rm -rf "$tmp_volume_dir"
 fi
