feat: google_app_cred is in tmp folder

diff --git a/binzx/otomi b/binzx/otomi
--- a/binzx/otomi
+++ b/binzx/otomi
@@ -132,9 +132,6 @@ if [[ $base_dir == *"otomi-core"* ]] || [[ $(pwd) == *"otomi-core"* ]]; then
     stack_dir=$(pwd | awk -F'otomi-core' '{print $1"otomi-core"}')
   fi
 
-  stack_volume="${stack_dir} ${stack_dir}"
-  tmp_volume="/tmp /tmp"
-
   if [ -f "${stack_dir}/dist/otomi.js" ]; then # Use development distribution if exists
     executable="node --experimental-specifier-resolution=node ${stack_dir}/dist/otomi.js --"
   fi
@@ -155,39 +152,47 @@ if [ "$status" -ne 0 ]; then
 fi
 
 function mount_with_named_volume() {
+  source=$1
+  dest=$2
   [ -z "$NAMED_VOLUME" ] && export NAMED_VOLUME='otomi-volume'
   helper_container_name="otomi-volume-helper"
 
-  source_files=$1
-  destination_path=$2
+  [ -z "$source" ] && echo "Error in function 'mount_with_named_volume': source path is empty" 1>&2
 
-  docker container inspect $helper_container_name >/dev/null 2>&1 && docker rm $helper_container_name >/dev/null 2>&1
-  docker container create --name $helper_container_name -v $NAMED_VOLUME:$destination_path hello-world >/dev/null 2>&1 &&
-    cd $source_files >/dev/null 2>&1 && docker cp . $helper_container_name:$destination_path >/dev/null 2>&1 &&
-    docker rm $helper_container_name >/dev/null 2>&1
+  { # Create volume and copy over contents
+    docker container inspect $helper_container_name && docker rm $helper_container_name
+    docker container create --name $helper_container_name -v "$NAMED_VOLUME:$dest" hello-world &&
+      cd "$source" && docker cp . "$helper_container_name:$dest" &&
+      docker rm $helper_container_name
+  } >/dev/null 2>&1
 
-  echo "$NAMED_VOLUME:$destination_path"
+  echo "$NAMED_VOLUME:$dest"
 }
 
-docker run --network host --rm -it \
-  -v $(mount_with_named_volume $stack_volume) \
-  -v $(mount_with_named_volume $tmp_volume) \
-  -v $(mount_with_named_volume ${KUBECONFIG:-$HOME/.kube} /home/app/.kube) \
-  -v $HOME/.ssh:/home/app/.ssh \
-  -v $helm_config:/home/app/.config/helm \
-  -v $HOME/.config/gcloud:/home/app/.config/gcloud \
-  -v $HOME/.aws:/home/app/.aws \
-  -v $HOME/.azure:/home/app/.azure \
-  -v ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS} \
-  -v $ENV_DIR:$stack_dir/env \
-  -v $ENV_DIR:$ENV_DIR \
-  --env-file $tmp_env \
-  -w $stack_dir \
-  $otomi_tools_image \
-  bash -c "$cmd"
+function drun() {
+  docker run --network host --rm -it \
+    -v $(mount_with_named_volume "$stack_dir" "$stack_dir") \
+    -v $(mount_with_named_volume /tmp /tmp) \
+    -v $(mount_with_named_volume "${KUBECONFIG:-$HOME/.kube}" /home/app/.kube) \
+    -v $(mount_with_named_volume "$HOME/.ssh" /home/app/.ssh) \
+    -v $(mount_with_named_volume "$helm_config" /home/app/.config/helm) \
+    -v $(mount_with_named_volume "$HOME/.config/gcloud" /home/app/.config/gcloud) \
+    -v $(mount_with_named_volume "$HOME/.aws" /home/app/.aws) \
+    -v $(mount_with_named_volume "$HOME/.azure" /home/app/.azure) \
+    -v $(mount_with_named_volume "$ENV_DIR" "$stack_dir/env") \
+    -v $(mount_with_named_volume "$ENV_DIR" "$ENV_DIR") \
+    --env-file "$tmp_env" \
+    -w "$stack_dir" \
+    "$otomi_tools_image" \
+    bash -c "$cmd"
+}
 
-status=$?
-rm -f "$tmp_env"
-set +x
-docker volume rm $NAMED_VOLUME >/dev/null 2>&1 &&
-  exit $status
+function main() {
+  drun
+  status=$?
+  rm -f "$tmp_env"
+  docker volume rm $NAMED_VOLUME >/dev/null 2>&1 &&
+    exit $status
+}
+
+main
