refactor: 💡 Refactor variables in shell scripts

diff --git a/binzx/otomi b/binzx/otomi
--- a/binzx/otomi
+++ b/binzx/otomi
@@ -24,12 +24,12 @@ if [ -z ${ENV_DIR+x} ]; then
 else
   mkdir -p $ENV_DIR
 fi
-THIS_IS_BASH=$(ps -o ppid= $$)
-EXECUTIING_SHELL=$(ps -o comm= $THIS_IS_BASH | sed "s/[^[:alnum:]\/]//g")
-PATH_TO_EXEC_SHELL=$(which $EXECUTIING_SHELL)
+this_is_bash=$(ps -o ppid= $$)
+executing_shell=$(ps -o comm= $this_is_bash | sed "s/[^[:alnum:]\/]//g")
+path_to_exec_shell=$(which $executing_shell)
 # TODO: change image tag to latest
-DOCKER_TAG=${DOCKER_TAG:-otomi-zx}
-readonly otomi_tools_image="otomi/core:${DOCKER_TAG}"
+OTOMI_TAG=${OTOMI_TAG:-otomi-zx}
+readonly otomi_tools_image="otomi/core:${OTOMI_TAG}"
 # shellcheck disable=SC2155
 readonly base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 readonly callingArgs="$*"
@@ -39,16 +39,16 @@ if [[ ${BASH_SOURCE[0]} == '/'*  ]]; then
 fi
 readonly scriptFullPath
 
-UPDATE_BASE="https://raw.githubusercontent.com/redkubes/otomi-core/${DOCKER_TAG}/binzx/otomi"
+update_base="https://raw.githubusercontent.com/redkubes/otomi-core/${OTOMI_TAG}/binzx/otomi"
 
 runSelfUpdate() {
   echo "Performing self-update..."
 
   # Download new version
   echo -n "Downloading latest version..."
-  if ! wget --quiet --output-document="$0.tmp" $UPDATE_BASE ; then
+  if ! wget --quiet --output-document="$0.tmp" $update_base ; then
     echo "Failed: Error while trying to wget new version!"
-    echo "File requested: $UPDATE_BASE"
+    echo "File requested: $update_base"
     exit 1
   fi
   echo "Done."
@@ -85,7 +85,7 @@ checkUpdate() {
     return 0
   fi
 
-  lastCommitDate=$(curl -s "https://api.github.com/repos/redkubes/otomi-core/commits?sha=${DOCKER_TAG}&path=binzx%2Fotomi&page=1&per_page=1" | grep -A5 '"committer":' | grep '"date":' | awk -F': ' '{print $2}')
+  lastCommitDate=$(curl -s "https://api.github.com/repos/redkubes/otomi-core/commits?sha=${OTOMI_TAG}&path=binzx%2Fotomi&page=1&per_page=1" | grep -A5 '"committer":' | grep '"date":' | awk -F': ' '{print $2}')
   lastFileChange=$(date -u -r $scriptFullPath "+%Y-%m-%dT%H:%M:%SZ")
   lastCommitDate=$(echo $lastCommitDate | tr -d '"')
   lastCommitDateSec=$(date --date="$lastCommitDate" +%s)
@@ -110,8 +110,8 @@ tmpEnv=$(mktemp)
 env | grep -v -e ^PATH= -e ^HOME= -e ^USER= -e ^TMPDIR= >$tmpEnv
 
 cat >> $tmpEnv << EOF
-SHELL=${PATH_TO_EXEC_SHELL}
-DOCKER_TAG=${DOCKER_TAG}
+SHELL=${path_to_exec_shell}
+OTOMI_TAG=${OTOMI_TAG}
 OTOMI_CALLER_COMMAND=${BASH_SOURCE[0]##*/}
 OTOMI_IN_DOCKER=true
 EOF
@@ -146,7 +146,7 @@ pullOutput=$(docker pull $otomi_tools_image 2>&1 >/dev/null)
 status=$?
 if [ "$status" -ne 0 ]; then
   echo "$pullOutput"
-  echo "Could not find an image for the supplied DOCKER_TAG: '${DOCKER_TAG}'"
+  echo "Could not find an image for the supplied OTOMI_TAG: '${OTOMI_TAG}'"
   exit $status
 fi
 
