feat: updated patch version bump logic so it is not bumped on every push of the main branch

diff --git a/.github/workflows/cloudtty-build-push.yml b/.github/workflows/cloudtty-build-push.yml
--- a/.github/workflows/cloudtty-build-push.yml
+++ b/.github/workflows/cloudtty-build-push.yml
@@ -26,8 +26,8 @@ jobs:
 
           set -e
 
-          # Set the first image version to '0.1.0' if the repo does  not exists.
-          if ! curl -s -L --fail "https://hub.docker.com/v2/repositories/${{ env.NAMESPACE }}/${{ env.REPO }}"; then echo "NEW_VERSION=0.1.0" >> $GITHUB_ENV && exit 0; fi
+          # # Set the first image version to '0.1.0' if the repo does  not exists.
+          # if ! curl -s -L --fail "https://hub.docker.com/v2/repositories/${{ env.NAMESPACE }}/${{ env.REPO }}"; then echo "NEW_VERSION=0.1.0" >> $GITHUB_ENV && exit 0; fi
 
           # Get data for latest 1000 versions of the image and filter the ones matching our semver pattern. Set the OLD_VERSION environment variable to the latest version.
           # The grep command matches the strings following this pattern: starts with an up to 2 digits number, a dot, an up to 3 digit number, a dot, ends with an up to 4 digits number
@@ -39,8 +39,8 @@ jobs:
           elif git log --format=%B -n 1 ${{ github.sha }} | grep -q "\[MINOR\]"; then
             # If a "[MINOR]" commit is found, increment the minor version by one and reset the patch version to '0'.
             echo "NEW_VERSION=$(echo ${OLD_VERSION} | awk -F. -v OFS=. '{$2 = $2 + 1; $3 = 0} {print $0}')" >> $GITHUB_ENV
-          else
-            # No special tag found, increment only the patch version by one.
+          elif git log  --name-only --oneline  | sed -n '2 p' | grep -q "\.tools\/Dockerfile-tty"
+            # No special tag found, but changes were made to the .tools/Dockerfile-tty so will upgrade the patch version.
             echo "NEW_VERSION=$(echo ${OLD_VERSION} | awk -F. -v OFS=. '{$3 = $3 + 1} {print $0}')" >> $GITHUB_ENV
             echo $NEW_VERSION
           fi
@@ -59,21 +59,3 @@ jobs:
       - name: Push Docker image
         run: |
           docker push ${{ env.NAMESPACE }}/${{ env.REPO }}:${{ env.NEW_VERSION }}
-
-      # - name: Pull from ghcr and re-tag
-      #   run: |
-      #     docker pull
-      #     docker tag
-
-      # - name: Login to Docker Hub
-      #   uses: docker/login-action@v2.1.0
-      #   with:
-      #     username: otomi
-      #     password: '${{ secrets.DOCKERHUB_OTOMI_TOKEN }}'
-
-      # - name: Push Docker image
-      #   run: |
-      #     docker pull
-      #     docker push $REPO:${{ env.NEW_VERSION }}
-      #     docker tag $REPO:${{ env.NEW_VERSION }} $REPO:latest
-      #     docker push $REPO:latest
